# Generated by Django 2.1.2 on 2018-11-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
        ),
    ]
